#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

apt-get update && apt-get install -y cron

python manage.py crontab add
python manage.py crontab show
python manage.py migrate
exec python manage.py runserver 0.0.0.0:8000
