# Generated by Django 4.2.13 on 2024-05-27 12:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogoGen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logo',
            name='img',
        ),
        migrations.AddField(
            model_name='logo',
            name='color',
            field=models.CharField(default=' ', max_length=32),
        ),
        migrations.AddField(
            model_name='logo',
            name='name',
            field=models.CharField(default='null', max_length=64),
        ),
        migrations.AddField(
            model_name='logo',
            name='number',
            field=models.IntegerField(default=10, validators=[django.core.validators.MaxValueValidator(25), django.core.validators.MinValueValidator(10)]),
        ),
    ]
