# Generated by Django 4.2.13 on 2024-05-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogoGen', '0002_remove_logo_img_logo_color_logo_name_logo_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
