# Generated by Django 4.2.13 on 2024-05-27 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LogoGen', '0003_alter_logo_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logo',
            name='number',
        ),
    ]
