# Generated by Django 4.2.13 on 2024-05-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogoGen', '0006_alter_logo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
