# Generated by Django 4.2.13 on 2024-05-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogoGen', '0007_alter_logo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='logo',
            name='taken',
            field=models.BooleanField(default=False),
        ),
    ]
