# Generated by Django 4.2.13 on 2024-05-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogoGen', '0008_logo_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='img',
            field=models.CharField(default='', max_length=50000),
        ),
    ]
